### ISSUE TITLE
Agreement Form - Group 26

### ISSUE THREAD

**Issue by TafadzwaManyenga** [TafadzwaManyenga/299-KAPT-QUT#1]
[Team Agreement.docx](https://github.com/TafadzwaManyenga/299-KAPT-QUT/files/1766582/Team.Agreement.docx)

**Comment by katrinaparsons** [comment]
[Team.Agreement.docx](https://github.com/TafadzwaManyenga/299-KAPT-QUT/files/1788528/Team.Agreement.docx)
